### ISSUE TITLE
svtopovz fails in flip_inverted_blocks

### ISSUE THREAD

**Issue by byoo** [PacificBiosciences/HiFi-SVTopo#3]
Hello,
I am trying SVTopo on a BAM file without running `sawfish`.
`svtopo` finished successfully but `svtopovz` failed as follows. Could you help troubleshoot the issue?

```
+ svtopovz --json svtopo_tb104_output.json.gz --out-prefix images/tb104_svtopo

SVTopoVz v0.1.2
Traceback (most recent call last):
  File "/sched/software/python/conda/envs/svtopo/bin/svtopovz", line 33, in <module>
    sys.exit(load_entry_point('svtopovz==0.1.2', 'console_scripts', 'svtopovz')())
  File "/sched/software/python/conda/envs/svtopo/lib/python3.10/site-packages/svtopovz-0.1.2-py3.10.egg/svtopovz/__main__.py", line 107, in main
    svtopovz(args)
  File "/sched/software/python/conda/envs/svtopo/lib/python3.10/site-packages/svtopovz-0.1.2-py3.10.egg/svtopovz/svtopovz.py", line 334, in svtopovz
    figname_splits = create_complex_sv_image(
  File "/sched/software/python/conda/envs/svtopo/lib/python3.10/site-packages/svtopovz-0.1.2-py3.10.egg/svtopovz/svtopovz.py", line 274, in create_complex_sv_image
    chain_plotted = plot_chain_representation(
  File "/sched/software/python/conda/envs/svtopo/lib/python3.10/site-packages/svtopovz-0.1.2-py3.10.egg/svtopovz/chain_plotter.py", line 36, in plot_chain_representation
    sample_paths = generate_sample_ordered_blocks(
  File "/sched/software/python/conda/envs/svtopo/lib/python3.10/site-packages/svtopovz-0.1.2-py3.10.egg/svtopovz/chain_plotter.py", line 179, in generate_sample_ordered_blocks
    extended_sample_paths = flip_inverted_blocks(extended_sample_paths)
  File "/sched/software/python/conda/envs/svtopo/lib/python3.10/site-packages/svtopovz-0.1.2-py3.10.egg/svtopovz/chain_plotter.py", line 246, in flip_inverted_blocks
    for i in range(len(sample_paths)):
TypeError: object of type 'NoneType' has no len()
```

**Comment by jbelyeu** [comment]
Apologies for the oversight in that new function. I've just pushed a new patch to the repo, which will allow you to test immediately if you want to install svtopovz from a repo clone. I'll work next on cutting a new release and then on a conda update, which will take a little longer.

**Comment by byoo** [comment]
It works. Thank you for the quick fix!
I'd like to report that the Reference path/Sample path sometimes gets overlapped. Here's an example:
![tb104_svtopo-chr10_56556869_56576045-chr6_69889433_69889769-chr8_106788848_106791750](https://github.com/user-attachments/assets/0b900e8f-1fc6-45f9-bc04-d3cf0c0579a6)

**Comment by jbelyeu** [comment]
Glad to hear that worked! Will work on the overlapping issue, that may take a little more time to correct
